# GLOBAL SITE SETTINGS

cname: berrillwatson.yourwebvisual.com

# META
title: Berrill & Watson
title_homepage: Berrill & Watson - Your Superannuation and Insurance Lawyers
company: Berrill & Watson Lawyers
description: Berrill & Watson is a law firm for everyday people and businesses. We believe strongly in pursuing the rights of our clients and making the law more accessible and easier to understand.

# DEVELOPER
allow_robots: false
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/berrill-0717
github_repo_name:
jekyll_version: 3.5.0

# OFFICES
offices:
  - title: Victoria
    address: Suite 5, Number 4 Homer Street<br> Moonee Ponds VIC 3039
    phone: 03 9448 8048
    email: info@berrillwatson.com.au

  - title: Queensland
    address: 7/199 George Street<br> Brisbane QLD 4003
    phone: 07 3166 9034
    email: info@berrillwatson.com.au

# SOCIAL MEDIA
facebook:
linked_in:
google_plus:
instagram:

# GOOGLE
google_analytics: "UA-XXXXXXXX-X"

# AUTHOR
author:
  title: Much Media
  url: http://muchmedia.com.au
  logo: /assets/img/ui/logo-much-media.svg
  description: WEBSITE BY MUCH MEDIA